windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = rainlight-launcher
    match:class = ^(dev.afterrain.Rainlight|rainlight)$
    float = true
    center = true
    size = 780 570
    stay_focused = true
}

windowrule {
    name = fix-xwayland-drag
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = after-rain-tools
    match:class = ^(after-rain-audio|after-rain-network|after-rain-bluetooth)$
    float = true
    center = true
    size = 1400 900
}

layerrule {
    name = waybar-blur
    match:namespace = waybar
    blur = true
    ignore_alpha = 0.15
}

layerrule {
    name = swaync-blur
    match:namespace = swaync-control-center
    blur = true
    ignore_alpha = 0.15
}

layerrule {
    name = launcher-blur
    match:namespace = hyprlauncher
    blur = true
    ignore_alpha = 0.15
}
