exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = pgrep -x ibus-daemon >/dev/null || ibus-daemon -drx
exec-once = pgrep -x hyprpaper >/dev/null || hyprpaper
exec-once = pgrep -x hypridle >/dev/null || hypridle
exec-once = pgrep -x waybar >/dev/null || env GDK_BACKEND=wayland waybar
exec-once = pgrep -x hyprlauncher >/dev/null || hyprlauncher --daemon
exec-once = systemctl --user start swaync.service
