exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/bin/ibus-daemon -drx
exec-once = pgrep -x hyprpaper >/dev/null || hyprpaper
exec-once = pgrep -x hypridle >/dev/null || hypridle
exec-once = pgrep -x waybar >/dev/null || env GDK_BACKEND=wayland waybar
exec-once = $afterRainBin/after-rain-workspace watch
exec-once = systemctl --user start swaync.service
exec-once = systemctl --user start swayosd.service
exec-once = systemctl --user start hyprpolkitagent.service
exec-once = systemctl --user start xdg-desktop-portal-hyprland.service
