exec-once = $afterRainBin/after-rain-session-start
exec-once = $afterRainBin/after-rain-ibus-wayland
exec-once = pgrep -x hyprpaper >/dev/null || hyprpaper
exec-once = pgrep -x hypridle >/dev/null || hypridle
exec-once = pgrep -x waybar >/dev/null || env GDK_BACKEND=wayland waybar
exec-once = $afterRainBin/after-rain-workspace watch
