local programs = require("after_rain.programs")

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("pgrep -x ibus-daemon >/dev/null || /usr/bin/ibus-daemon -drx")
    hl.exec_cmd("pgrep -x hyprpaper >/dev/null || hyprpaper")
    hl.exec_cmd("pgrep -x hypridle >/dev/null || hypridle")
    hl.exec_cmd("pgrep -x waybar >/dev/null || env GDK_BACKEND=wayland waybar")
    hl.exec_cmd(programs.bin .. "/after-rain-workspace watch")
    hl.exec_cmd("(test -x " .. programs.bin .. "/qs || command -v qs >/dev/null 2>&1 || command -v quickshell >/dev/null 2>&1) && systemctl --user start after-rain-shell.service || true")
    hl.exec_cmd("systemctl --user start swaync.service")
    hl.exec_cmd("systemctl --user start swayosd.service")
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland.service")
end)
