-- Generated by scripts/render-theme.py; do not edit directly.
return {
    colors = {
        background = "rgb(0b1018)",
        surface = "rgb(131b27)",
        surface_high = "rgb(1d2938)",
        foreground = "rgb(d8dee9)",
        muted = "rgb(7f8c9d)",
        accent = "rgb(72b7c8)",
        accent_warm = "rgb(d1a36f)",
        success = "rgb(82b58b)",
        warning = "rgb(d1a36f)",
        urgent = "rgb(e06c75)",
    },
    geometry = { radius = 14, gap_inner = 6, gap_outer = 12, border = 2 },
}
