#!/usr/bin/env python3
"""Render every color-driven component from one theme TOML file."""

from __future__ import annotations

import argparse
import difflib
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def rgb(value: str) -> str:
    value = value.removeprefix("#")
    return ", ".join(str(int(value[i : i + 2], 16)) for i in (0, 2, 4))


def css(colors: dict[str, str], opacity: dict[str, float]) -> str:
    lines = ["/* Generated by scripts/render-theme.py; do not edit directly. */"]
    lines.extend(f"@define-color {name} {value};" for name, value in colors.items())
    lines.append(f"@define-color panel rgba({rgb(colors['background'])}, {opacity['panel']});")
    lines.append(f"@define-color overlay rgba({rgb(colors['background'])}, {opacity['overlay']});")
    return "\n".join(lines) + "\n"


def hypr(colors: dict[str, str], geometry: dict[str, int]) -> str:
    lines = ["# Generated by scripts/render-theme.py; do not edit directly."]
    lines.extend("$" + f"{name} = rgb({value.removeprefix('#')})" for name, value in colors.items())
    lines.extend("$" + f"{name} = {value}" for name, value in geometry.items())
    return "\n".join(lines) + "\n"


def hyprtoolkit(colors: dict[str, str], geometry: dict[str, int]) -> str:
    def rgba(role: str) -> str:
        return f"rgba({colors[role].removeprefix('#')}ff)"

    return "\n".join(
        [
            "# Generated by scripts/render-theme.py; do not edit directly.",
            f"background = {rgba('background')}",
            f"base = {rgba('surface')}",
            f"text = {rgba('foreground')}",
            f"alternate_base = {rgba('surface_high')}",
            f"bright_text = {rgba('bright_text') if 'bright_text' in colors else rgba('foreground')}",
            f"link_text = {rgba('accent')}",
            f"accent = {rgba('accent')}",
            f"accent_secondary = {rgba('accent_warm')}",
            f"rounding_large = {geometry['radius']}",
            "rounding_small = 10",
            "h1_size = 20",
            "h2_size = 16",
            "h3_size = 14",
            "font_size = 12",
            "small_font_size = 11",
            "icon_theme = Yaru-prussiangreen",
            "font_family = Noto Sans CJK SC",
            "font_family_monospace = Ubuntu Sans Mono",
            "",
        ]
    )


def terminal_outputs(
    colors: dict[str, str], terminal: dict[str, str], opacity: dict[str, float]
) -> tuple[str, str]:
    order = [
        "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
        "bright_black", "bright_red", "bright_green", "bright_yellow",
        "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
    ]
    ghostty = [
        "# Generated by scripts/render-theme.py; do not edit directly.",
        f"background = {colors['background'].removeprefix('#')}",
        f"foreground = {colors['foreground'].removeprefix('#')}",
        f"selection-background = {colors['surface_high'].removeprefix('#')}",
        f"selection-foreground = {colors['foreground'].removeprefix('#')}",
        f"cursor-color = {colors['accent'].removeprefix('#')}",
    ]
    ghostty.extend(f"palette = {index}={terminal[name]}" for index, name in enumerate(order))
    ghostty.extend(
        [
            f"background-opacity = {opacity['terminal']}",
            "background-blur-radius = 24",
            "window-padding-x = 12",
            "window-padding-y = 10",
            "font-family = Ubuntu Sans Mono",
            "font-size = 11",
        ]
    )
    kitty = [
        "# Generated by scripts/render-theme.py; do not edit directly.",
        f"foreground            {colors['foreground']}",
        f"background            {colors['background']}",
        f"selection_foreground  {colors['foreground']}",
        f"selection_background  {colors['surface_high']}",
        f"cursor                {colors['accent']}",
    ]
    kitty.extend(f"color{index:<2}               {terminal[name]}" for index, name in enumerate(order))
    kitty.extend([f"background_opacity {opacity['terminal']}", "window_padding_width 10"])
    return "\n".join(ghostty) + "\n", "\n".join(kitty) + "\n"


def btop(colors: dict[str, str]) -> str:
    entries = {
        "main_bg": colors["background"], "main_fg": colors["foreground"],
        "title": colors["foreground"], "hi_fg": colors["accent"],
        "selected_bg": colors["surface_high"], "selected_fg": colors["foreground"],
        "inactive_fg": colors["muted"], "proc_misc": colors["accent"],
        "cpu_box": colors["muted"], "mem_box": colors["muted"],
        "net_box": colors["muted"], "proc_box": colors["muted"], "div_line": colors["muted"],
    }
    gradients = {
        "temp": ("success", "warning", "urgent"),
        "cpu": ("accent", "accent_warm", "urgent"),
        "free": ("success", "accent", "muted"),
        "cached": ("accent", "accent_warm", "warning"),
        "available": ("success", "accent", "accent_warm"),
        "used": ("accent", "warning", "urgent"),
        "download": ("muted", "accent", "success"),
        "upload": ("muted", "accent_warm", "urgent"),
    }
    lines = ["# Generated by scripts/render-theme.py; do not edit directly."]
    lines.extend(f'theme[{name}]="{value}"' for name, value in entries.items())
    for name, roles in gradients.items():
        for suffix, role in zip(("start", "mid", "end"), roles):
            lines.append(f'theme[{name}_{suffix}]="{colors[role]}"')
    return "\n".join(lines) + "\n"


def gtk(colors: dict[str, str]) -> str:
    roles = {
        "accent_color": "accent", "accent_bg_color": "accent",
        "accent_fg_color": "background", "window_bg_color": "background",
        "window_fg_color": "foreground", "view_bg_color": "surface",
        "view_fg_color": "foreground", "headerbar_bg_color": "surface",
        "headerbar_fg_color": "foreground", "card_bg_color": "surface_high",
        "card_fg_color": "foreground", "destructive_bg_color": "urgent",
    }
    lines = ["/* Generated by scripts/render-theme.py; do not edit directly. */"]
    lines.extend(f"@define-color {name} {colors[role]};" for name, role in roles.items())
    lines.extend(
        [
            "window, .background { background-color: @window_bg_color; color: @window_fg_color; }",
            "headerbar { background-color: @headerbar_bg_color; box-shadow: none; }",
            "popover, menu { background-color: @view_bg_color; color: @view_fg_color; }",
            "selection { background-color: @accent_bg_color; color: @accent_fg_color; }",
        ]
    )
    return "\n".join(lines) + "\n"


def render(theme: Path) -> dict[Path, str]:
    with theme.open("rb") as handle:
        data = tomllib.load(handle)
    colors, geometry = data["colors"], data["geometry"]
    terminal, opacity = data["terminal"], data["opacity"]
    ghostty, kitty = terminal_outputs(colors, terminal, opacity)
    shared_css = css(colors, opacity)
    return {
        ROOT / "config/hypr/conf.d/05-theme.conf": hypr(colors, geometry),
        ROOT / "config/hypr/hyprtoolkit.conf": hyprtoolkit(colors, geometry),
        ROOT / "config/waybar/colors.css": shared_css,
        ROOT / "config/swaync/colors.css": shared_css,
        ROOT / "config/wlogout/colors.css": shared_css,
        ROOT / "config/swayosd/colors.css": shared_css,
        ROOT / "config/rainlight/colors.css": shared_css,
        ROOT / "config/ghostty/config": ghostty,
        ROOT / "config/kitty/after-rain.conf": kitty,
        ROOT / "config/btop/themes/after-rain.theme": btop(colors),
        ROOT / "config/gtk-3.0/gtk.css": gtk(colors),
        ROOT / "config/gtk-4.0/gtk.css": gtk(colors),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--theme", default="themes/after-rain/colors.toml")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failed = False
    for path, expected in render(ROOT / args.theme).items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if args.check and actual != expected:
            failed = True
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
            print("".join(difflib.unified_diff(actual.splitlines(True), expected.splitlines(True))), file=sys.stderr)
        elif not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            print(path.relative_to(ROOT))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
